### ISSUE TITLE
Grading of tuning curves for large logo on white background

### ISSUE THREAD

**Issue by jgosmann** [nengo/design#4]
The guide says:

> The opacity of the tuning curves are graded from top to bottom for visual effect when the logo is large enough.

However, the tuning curves in the Nengo DL logo are not graded. Is this by accident (because the base logo uses three different colors and is therefore not graded), or should only the logo for dark background be graded? If it should be graded on the light background, shall I copy the opacity values from the logo for the dark version?

**Comment by drasmuss** [comment]
I tried it out with graded values, and thought it looked better without in the NengoDL case (I can't remember exactly why, I think I remember having trouble finding a range of opacity values that worked on the high and low end with the orange).  I'd say just go with whatever looks better to you 🤷‍♀️

**Comment by tbekolay** [comment]
Yeah we can remove that restriction from the guidelines if the consensus is that doesn't look great.

**Comment by drasmuss** [comment]
Ah yeah I'm remembering a bit more now.  I think it was basically that on the white background I had to set the minimum opacity pretty high for it to be visible, and then it was so high that you really couldn't see much of a gradation between the high and low.  So I thought why bother and just went with solid throughout.

**Comment by tbekolay** [comment]
Yeah that makes sense. I had similar thoughts for the dark Nengo logo (I think), but at the same time it's kind of bland without the grading. So maybe we should codify having it only in the dark logo? The dark logo isn't used very often anyhow.

**Comment by jgosmann** [comment]
I just tried it with the WIP Nengo SPA logo (opacity values 100%, 75%, 60%) and I think I prefer it to the ungraded version.

![full-logo-light](https://user-images.githubusercontent.com/850157/39150880-ab7661d0-4711-11e8-94ab-f401acfb5f25.png)
![full-logo-light](https://user-images.githubusercontent.com/850157/39150051-0fb099fc-470f-11e8-835d-1c398444ac01.png)

**Comment by bmorcos** [comment]
Do we want to close this now that we've merged in #7? or is this still up for debate?

**Comment by tbekolay** [comment]
> Do we want to close this now that we've merged in #7?

Yes! If we revisit this decision it will affect a bunch of logos, so that'll be a big job.
