### ISSUE TITLE
What should we use for project logos?

### ISSUE THREAD

**Issue by tbekolay** [nengo/design#9]
With the new Sphinx theme, each project's docs should feature their logo because without it there's no obvious way to get back to the doc index page. Currently we've got competing standards, with [NengoDL using the square logo](https://www.nengo.ai/nengo-dl/) and [Nengo design using a full logo](https://www.nengo.ai/design/)

We're having to decide this now for Nengo Loihi, so it makes sense to have this be a decision that will stick for all the repos (if there are objections to standardizing them feel free to voice them here, but I think generally we all like having fewer decisions). One of the possible options requires some additional assets, so it'll impact the design repo in general.

### Option 1: full-light logo (vote with :smile:)

![full-logo](https://user-images.githubusercontent.com/203709/49316626-85788880-f4bf-11e8-9d00-0c0355fd6a3a.png)

### Option 2: square logo (vote with :tada:)

![square-logo](https://user-images.githubusercontent.com/203709/49316633-89a4a600-f4bf-11e8-97bd-2f8b0ced6800.png)

### Option 3: full-light logo, but with only non-Nengo part (vote with :heart:)

![half-logo](https://user-images.githubusercontent.com/203709/49316643-8e695a00-f4bf-11e8-8b43-4337d2f15416.png)

---

Also, try to not make the decision based on the size of the logo ... I made a new issue (https://github.com/nengo/nengo-sphinx-theme/issues/17) to make the logo size configurable in the theme, as some of these options will not work well with short project names and other won't work well with long project names.

**Comment by xchoo** [comment]
There's no 😆 face option to vote.

**Comment by tbekolay** [comment]
> There's no :laughing: face option to vote.

Not my fault github used a non-existent emoji in their emoji response list

**Comment by xchoo** [comment]
Is this it? 😄

**Comment by tbekolay** [comment]
Not my fault Github uses "smile" for their "laugh" reaction instead of "laughing" then

**Comment by xchoo** [comment]
😃

**Comment by tbekolay** [comment]
Looks like consensus enough for option 1, which to my eyes looks a bit small for Nengo Loihi, so I made https://github.com/nengo/nengo-sphinx-theme/pull/18 to be able to widen it.
